apiVersion: v1
kind: ConfigMap
metadata:
  name: school-saas-config
  namespace: school-saas
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  APP_PORT: "5000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "school_saas"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
