apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-saas

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml
- postgres.yaml
- redis.yaml
- ingress.yaml
- networkpolicies.yaml

commonLabels:
  app.kubernetes.io/name: school-saas
  app.kubernetes.io/instance: school-saas
  app.kubernetes.io/managed-by: kustomize
