apiVersion: v1
kind: Secret
metadata:
  name: school-saas-secrets
  namespace: school-saas
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmU=
